<a href="https://colab.research.google.com/github/Landres20/AnalisisDeAlgoritmos/blob/main/AnalisisDeAlgoritmos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

fibonaci iterativo

In [8]:
  def fibonaci_iterativo(x1):
      res=0
      i=0
      while i<=x1:
          res = res + i
          i = i + 1
          print(res)
    
      return res

  fibonaci_iterativo(3)

0
1
3
6


6

fibonaci recursivo

In [14]:
  def fibonaciRec(x):
      if x==1:
          return 0
      elif x==2:
          return 1
      else:
          num = (fibonaciRec(x-1)+fibonaciRec(x-2))
          print(num)
          return num
  fibonaciRec(3)

1


1

In [16]:
import random

def randomList(l):
    newList = []
    for i in range(0, l):
        n = random.randint(1, 99)
        newList.append(n);
    return newList

def bubbleSort(listLength):
    randList = randomList(listLength)
    print(randList)
    for listLengthIndex in range(len(randList)-1):
        for index in range(0, listLength-listLengthIndex-1):
            if randList[index] > randList[index+1]:
                swap = randList[index]
                randList[index] = randList[index+1]
                randList[index+1] = swap

    print('\nSorted:')
    print(randList)

bubbleSort(15)

[41, 26, 28, 29, 15, 39, 63, 64, 96, 39, 83, 75, 73, 18, 17]

Sorted:
[15, 17, 18, 26, 28, 29, 39, 39, 41, 63, 64, 73, 75, 83, 96]


Bubble Sort (grupo de William)

In [17]:
from random import seed
from random import randint
import numpy as np

def bubble_sort(cant):
    listaDesordenada = []
    seed(1)
    for _ in range(cant):
      listaDesordenada = np.append(listaDesordenada, randint(0,50))
    veces = 0
    for i in range(len(listaDesordenada)):
        for j in range(len(listaDesordenada) - 1):
            veces+=1
            if listaDesordenada[j] > listaDesordenada[j+1]:
                listaDesordenada[j], listaDesordenada[j+1] = listaDesordenada[j+1], listaDesordenada[j]
    print(listaDesordenada)
    return veces

ns=[10, 50, 100, 1000, 5000, 10000, 20000]
for n in ns:
  veces = bubble_sort(n);
  print(n , veces)

[ 4.  7.  8. 16. 28. 30. 31. 36. 48. 48.]
10 90
[ 0.  0.  1.  1.  1.  1.  1.  4.  6.  6.  7.  8. 13. 13. 14. 14. 14. 16.
 17. 20. 24. 24. 24. 27. 27. 28. 28. 28. 30. 31. 31. 31. 33. 34. 35. 36.
 37. 38. 41. 41. 43. 44. 46. 46. 48. 48. 48. 48. 49. 50.]
50 2450
[ 0.  0.  1.  1.  1.  1.  1.  1.  2.  4.  5.  6.  6.  6.  7.  7.  8. 11.
 11. 12. 13. 13. 14. 14. 14. 14. 14. 15. 16. 17. 18. 18. 18. 19. 20. 21.
 22. 23. 23. 24. 24. 24. 25. 25. 26. 26. 27. 27. 27. 28. 28. 28. 28. 29.
 30. 30. 31. 31. 31. 31. 32. 32. 32. 33. 34. 35. 35. 35. 36. 37. 37. 37.
 38. 40. 41. 41. 41. 42. 42. 43. 43. 43. 44. 44. 45. 46. 46. 46. 46. 47.
 47. 47. 48. 48. 48. 48. 48. 49. 49. 50.]
100 9900
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  2.  2.  2.  2.  2.  2.  2.  2.  2.
  2.  2.  2.  2.  2.  2.  2.  3.  3.  3.  3.  3.  3.  3.  3.  3.  4.  4.
  4.  4.  4.  4.  4.  4.  4.  4.

KeyboardInterrupt: ignored

Bubble sort cambiado a insertion sort

In [18]:
from random import seed
from random import randint
import numpy as np

def bubble_sort(cant):
  listaDesordenada = []
  seed(1)
  
  for _ in range(cant):
    listaDesordenada = np.append(listaDesordenada, randint(0, 50))
  
  print(listaDesordenada)
  
  veces = 0
  for i in range(len(listaDesordenada)):
    for j in range(i, 0, -1):
      veces += 1
      if listaDesordenada[j] < listaDesordenada[j-1]:
        listaDesordenada[j], listaDesordenada[j-1] = listaDesordenada[j-1], listaDesordenada[j]
      else:
        break
  
  print(listaDesordenada)
  return veces

bubble_sort(10)

[ 8. 36. 48.  4. 16.  7. 31. 48. 28. 30.]
[ 4.  7.  8. 16. 28. 30. 31. 36. 48. 48.]


27