<a href="https://colab.research.google.com/github/Landres20/AnalisisDeAlgoritmos/blob/main/AnalisisDeAlgoritmos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

fibonaci iterativo

In [ ]:
  def fibonaci_iterativo(x1):
      res=0
      i=0
      while i<=x1:
          res = res + i
          i = i + 1
          print(res)
    
      return res

  fibonaci_iterativo(3)

0
1
3
6


6

fibonaci recursivo

In [ ]:
  def fibonaciRec(x):
      if x==1:
          return 0
      elif x==2:
          return 1
      else:
          num = (fibonaciRec(x-1)+fibonaciRec(x-2))
          print(num)
          return num
  fibonaciRec(3)

1


1

In [ ]:
import random

def randomList(l):
    newList = []
    for i in range(0, l):
        n = random.randint(1, 99)
        newList.append(n);
    return newList

def bubbleSort(listLength):
    randList = randomList(listLength)
    print(randList)
    for listLengthIndex in range(len(randList)-1):
        for index in range(0, listLength-listLengthIndex-1):
            if randList[index] > randList[index+1]:
                swap = randList[index]
                randList[index] = randList[index+1]
                randList[index+1] = swap

    print('\nSorted:')
    print(randList)

bubbleSort(15)

[41, 26, 28, 29, 15, 39, 63, 64, 96, 39, 83, 75, 73, 18, 17]

Sorted:
[15, 17, 18, 26, 28, 29, 39, 39, 41, 63, 64, 73, 75, 83, 96]


Bubble Sort (grupo de William)

In [ ]:
from random import seed
from random import randint
import numpy as np

def bubble_sort(cant):
    listaDesordenada = []
    seed(1)
    for _ in range(cant):
      listaDesordenada = np.append(listaDesordenada, randint(0,50))
    veces = 0
    for i in range(len(listaDesordenada)):
        for j in range(len(listaDesordenada) - 1):
            veces+=1
            if listaDesordenada[j] > listaDesordenada[j+1]:
                listaDesordenada[j], listaDesordenada[j+1] = listaDesordenada[j+1], listaDesordenada[j]
    print(listaDesordenada)
    return veces

ns=[10, 50, 100, 1000, 5000, 10000, 20000]
for n in ns:
  veces = bubble_sort(n);
  print(n , veces)

[ 4.  7.  8. 16. 28. 30. 31. 36. 48. 48.]
10 90
[ 0.  0.  1.  1.  1.  1.  1.  4.  6.  6.  7.  8. 13. 13. 14. 14. 14. 16.
 17. 20. 24. 24. 24. 27. 27. 28. 28. 28. 30. 31. 31. 31. 33. 34. 35. 36.
 37. 38. 41. 41. 43. 44. 46. 46. 48. 48. 48. 48. 49. 50.]
50 2450
[ 0.  0.  1.  1.  1.  1.  1.  1.  2.  4.  5.  6.  6.  6.  7.  7.  8. 11.
 11. 12. 13. 13. 14. 14. 14. 14. 14. 15. 16. 17. 18. 18. 18. 19. 20. 21.
 22. 23. 23. 24. 24. 24. 25. 25. 26. 26. 27. 27. 27. 28. 28. 28. 28. 29.
 30. 30. 31. 31. 31. 31. 32. 32. 32. 33. 34. 35. 35. 35. 36. 37. 37. 37.
 38. 40. 41. 41. 41. 42. 42. 43. 43. 43. 44. 44. 45. 46. 46. 46. 46. 47.
 47. 47. 48. 48. 48. 48. 48. 49. 49. 50.]
100 9900
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  2.  2.  2.  2.  2.  2.  2.  2.  2.
  2.  2.  2.  2.  2.  2.  2.  3.  3.  3.  3.  3.  3.  3.  3.  3.  4.  4.
  4.  4.  4.  4.  4.  4.  4.  4.

KeyboardInterrupt: ignored

Bubble sort cambiado a insertion sort

In [ ]:
from random import seed
from random import randint
import numpy as np

def bubble_sort(cant):
  listaDesordenada = []
  seed(1)
  
  for _ in range(cant):
    listaDesordenada = np.append(listaDesordenada, randint(0, 50))
  
  print(listaDesordenada)
  
  veces = 0
  for i in range(len(listaDesordenada)):
    for j in range(i, 0, -1):
      veces += 1
      if listaDesordenada[j] < listaDesordenada[j-1]:
        listaDesordenada[j], listaDesordenada[j-1] = listaDesordenada[j-1], listaDesordenada[j]
      else:
        break
  
  print(listaDesordenada)
  return veces

bubble_sort(10)

[ 8. 36. 48.  4. 16.  7. 31. 48. 28. 30.]
[ 4.  7.  8. 16. 28. 30. 31. 36. 48. 48.]


27

//////////////////////////////////////SEMANA 2//////////////////////////////////////

In [1]:
##Busqueda Binaria
def busBinaria (lis, a, b, c): 
  
    if b >= a: 
  
        mid = a + (b - a) // 2
        if lis[mid] == c: 
            return mid 

        elif lis[mid] > c: 
            return busBinaria(lis, l, mid-1, c) 
  
        else: 
            return busBinaria(lis, mid + 1, b, c) 
  
    else: 
        return -1
  
lis = [ 2, 3, 4, 10, 40 ] 
c = 10
  
result = busBinaria(lis, 0, len(lis)-1, c) 
  
if result != -1: 
    print ("El elemento se encontro en la posicion:  % d" % result) 
else: 
    print ("El elemento que se buscaba no se encuentra en la lista!")

El elemento se encontro en la posicion:   3


In [5]:
## Merge sort 
def unir(lis, a, b, c): 
    n1 = b - a + 1
    n2 = c- b 
  
    x = [0] * (n1) 
    y = [0] * (n2) 
  
    for i in range(0 , n1): 
        x[i] = lis[a + i] 
  
    for j in range(0 , n2): 
        y[j] = lis[b + 1 + j] 
  
    i = 0     
    j = 0     
    k = a     
  
    while i < n1 and j < n2 : 
        if x[i] <= y[j]: 
            lis[k] = x[i] 
            i += 1
        else: 
            lis[k] = y[j] 
            j += 1
        k += 1
  
    while i < n1: 
        lis[k] = x[i] 
        i += 1
        k += 1
  
    while j < n2: 
        lis[k] = y[j] 
        j += 1
        k += 1
  
def meSort(lis,a,c): 
    if a < c: 
  
        b = (a+(c-1))//2
        meSort(lis, a, b) 
        meSort(lis, b+1, c) 
        unir(lis, a, b, c) 
  
lis = [12, 11, 13, 5, 6, 7] 
n = len(lis) 
print ("El arreglo desordenado: ") 
for i in range(n): 
    print ("%d" %lis[i]), 
  
meSort(lis,0,n-1) 
print ("\n\nArreglo ordenado: ") 
for i in range(n): 
    print ("%d" %lis[i]),

El arreglo desordenado: 
12
11
13
5
6
7


Arreglo ordenado: 
5
6
7
11
12
13


In [14]:
## Max Point Algorithm
def maxCrossingSum(lis, a, b, c) : 
      
    sm = 0; left_sum = -10000
      
    for i in range(b, a-1, -1) : 
        sm = sm + lis[i] 
          
        if (sm > left_sum) : 
            left_sum = sm 
      
    sm = 0; right_sum = -1000
    for i in range(b + 1, c + 1) : 
        sm = sm + lis[i] 
          
        if (sm > right_sum) : 
            right_sum = sm 
      
    return max(left_sum + right_sum, left_sum, right_sum) 
  
def maxSubArraySum(lis, l, h) : 
      
    if (l == h) : 
        return arr[l] 
  
    m = (l + h) // 2

    return max(maxSubArraySum(lis, l, m), 
               maxSubArraySum(lis, m+1, h), 
               maxCrossingSum(lis, l, m, h)) 
              
arr = [2, 3, 4, 5, 7] 
n = len(lis) 
  
max_sum = maxSubArraySum(lis, 0, n-1) 
print("Punto maximo ", max_sum)

Punto maximo  21


/////////////////////////////////SEMANA 3/////////////////////////////////

In [20]:
import math as m

points=[[3,7],[10,5],[4,8],[9,24],[12,6],[4,11],[10,3],[6,11]]

def amount(a, b):
    aa= (a[0]-b[0])**2
    bb= (a[1]-b[1])**2
    res= m.sqrt((aa+bb))
    return res


def min(list):
    first= True
    min=0
    max=0
    pair=[]
    pair2=[]
    for a in range(len(points)):
        for b in range(a+1,len(points)):
            n= amount(list[a],list[b])
            if first:
                first=False
                pair.append(list[a])
                pair.append(list[b])
                pair2.append(list[a])
                pair2.append(list[b])
                min=n
                max=n
            else:
                if n < min:
                    pair.clear()
                    pair.append(list[a])
                    pair.append(list[b])
                    min=0
                    min=n
                if n > max:
                    pair2.clear()
                    pair2.append(list[a])
                    pair2.append(list[b])
                    max=0
                    max=n
    
    print("The least distance between 2 points is ",min," the points are ",pair)
    print("The most distance between 2 points is ",max," the points are ",pair2)


min(points)

The least distance between 2 points is  1.4142135623730951  the points are  [[3, 7], [4, 8]]
The most distance between 2 points is  21.02379604162864  the points are  [[9, 24], [10, 3]]
